---
name: CI
'on':
  pull_request:
  push:

defaults:
  run:
    working-directory: 'nikosch86.pbs'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nikosch86/docker-alpine-ansible:v0.0.3
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'nikosch86.pbs'

      - name: Install test dependencies.
        run: pipx install yamllint

      - name: yamllint files
        run: |
          yamllint .

      - name: Ansible lint
        run: |
          ansible-lint .
