---
name: CI
'on':
  pull_request:
  push:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nikosch86/docker-alpine-ansible:v0.0.3
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install test dependencies.
        run: pipx install yamllint

      - name: yamllint files
        run: |
          yamllint .

      - name: Ansible lint
        run: |
          ansible-lint .
